services:
  - type: web
    name: golive-tracker
    runtime: python
    buildCommand: pip install -r requirements.txt
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: golive-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: golive-db
    plan: free
